### ISSUE TITLE
Kavita on Tachiyomi J2K series list incomplete

### ISSUE THREAD

**Issue by Cwavs** [ThePromidius/kavita-tachiyomi-extension#33]
### Source information and language

Kavita 1.4.10

### Steps to reproduce

1. Install and set up Kavita as per the [guide](https://wiki.kavitareader.com/en/guides/misc/tachiyomi)
2. Open to browse

### Expected behavior

A full list of all series are shown

### Actual behavior

An incomplete list is shown with some series missing.

### Tachiyomi version

J2K 1.6.6

### Android version

Android 11

### Other details

Issue is not present on normal Tachiyomi 0.14.6. I'm not sure if this is the right place to ask or if this should be considered a J2K issue. For me I noticed a few series were missing, but specifically Invincible is one of the one's present on Tachiyomi and the web app but not J2K
![Kavita](https://github.com/ThePromidius/kavita-tachiyomi-extension/assets/16854045/50d4257f-b656-45af-9395-fd935adcf7af)
![Tachiyomi](https://github.com/ThePromidius/kavita-tachiyomi-extension/assets/16854045/068d7107-18f8-4834-ab9d-27f546bd4534)
![Tachiyomi J2K](https://github.com/ThePromidius/kavita-tachiyomi-extension/assets/16854045/c2914925-5a7f-468f-8f3a-4b71f0ca18a3)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by scare376** [comment]
If it's working fine with the base app then it's a j2k issue and you can try to get some support there. This was made to work with the base tachiyomi app and is not guaranteed to work with forks.

**Comment by Cwavs** [comment]
Understood! Thanks for your help.
